name: child

on:
  workflow_call:
    inputs:
      paths:
        required: true
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: ${{ inputs.paths }}
    steps:
      - run: echo ${{ matrix.path }}
