name: child

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:${{ fromJson(inputs.target) }}
    steps:
      - run: echo ${{ matrix.path }}
