name: child

on:
  workflow_call:
    inputs:
      path_group:
        required: true
        type: string

jobs:
  apply:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: ${{ fromJson(inputs.path_group).paths }}
    steps:
      - run: echo ${{ matrix.path }}
