name: parent

on:
  push:
    branches:
      - main

jobs:
  main:
    strategy:
      matrix:
        paths: ['{ "paths": ["network", "storage"] }']
    uses: ./.github/workflows/child.yml
    with:
      target: ${{ matrix.paths }}
