name: parent

on:
  workflow_dispatch:
    inputs:
      hoge:
        required: true
        type: string
      env:
        required: true
        type: environment

jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - run: echo '${{ toJSON(github) }}'
  call_apply:
    strategy:
      max-parallel: 1
      matrix:
        path_group: ['{ "no": 1, "paths": ["network", "storage"] }', '{ "no": 2, "paths": ["app_01", "app_02"] }']
    uses: ./.github/workflows/child.yml
    with:
      path_group: ${{ matrix.path_group }}
