name: parent

on:
  push:
    branches:
      - main

jobs:
  main:
    strategy:
      matrix:
        paths: ['["network", "storage"]']
    uses: ./.github/workflows/child.yml
    with:
      paths: ${{ matrix.paths }}
