name: parent

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  call_apply:
    strategy:
      max-parallel: 1
      matrix:
        path_group: ['{ "no": 1, "paths": ["network", "storage"] }', '{ "no": 2, "paths": ["app_01", "app_02"] }']
    uses: ./.github/workflows/child.yml
    with:
      path_group: ${{ matrix.path_group }}
