name: parent

on:
  push:
    branches:
      - main

jobs:
  main:
    strategy:
      matrix:
        target: ["dev", "stage", "prod"]
    uses: ./.github/workflows/child.yml@main
    with:
      target: ${{ matrix.target }}
